/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package view;

/**
 *
 * @author Ventu
 */
public class ventanaprincipal extends javax.swing.JFrame {

    /** Creates new form ventanaprincipal */
    public ventanaprincipal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnTablaHuespedes = new javax.swing.JButton();
        btnTablaReservas = new javax.swing.JButton();
        btnTablaHabitaciones = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTablaHuespedes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Clientes.png"))); // NOI18N
        btnTablaHuespedes.setText("TABLA HUESPEDES");
        btnTablaHuespedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTablaHuespedesActionPerformed(evt);
            }
        });
        jPanel1.add(btnTablaHuespedes, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 240, -1));

        btnTablaReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/download (3).jpeg"))); // NOI18N
        btnTablaReservas.setText(" TABLA RESERVAS");
        btnTablaReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTablaReservasActionPerformed(evt);
            }
        });
        jPanel1.add(btnTablaReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 240, 30));

        btnTablaHabitaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/download (4).jpeg"))); // NOI18N
        btnTablaHabitaciones.setText(" TABLA DE HABITACIONES");
        btnTablaHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTablaHabitacionesActionPerformed(evt);
            }
        });
        jPanel1.add(btnTablaHabitaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 104, 240, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("SELECCIONE SU TABLA A  MOSTRAR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 280, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTablaHuespedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablaHuespedesActionPerformed
   listado_huespedes ventanaListadoHuespedes = new listado_huespedes();
        ventanaListadoHuespedes.setVisible(true);
       FormularioHuespedess formulario = new FormularioHuespedess(ventanaListadoHuespedes, true, "INS", 0);
formulario.setVisible(true);
    }//GEN-LAST:event_btnTablaHuespedesActionPerformed

    private void btnTablaReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablaReservasActionPerformed
       listado_reservas ventanaListadoReservas = new listado_reservas();
        ventanaListadoReservas.setVisible(true);
       FormularioReservas formulario = new FormularioReservas(ventanaListadoReservas, true, "INS", 0);
formulario.setVisible(true);
    }//GEN-LAST:event_btnTablaReservasActionPerformed

    private void btnTablaHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablaHabitacionesActionPerformed
        listado_habitaciones ventanaListadoHabitaciones = new listado_habitaciones();
        ventanaListadoHabitaciones.setVisible(true);
       FormularioHabitaciones formulario = new FormularioHabitaciones(ventanaListadoHabitaciones, true, "INS", 0);
formulario.setVisible(true);
    }//GEN-LAST:event_btnTablaHabitacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTablaHabitaciones;
    private javax.swing.JButton btnTablaHuespedes;
    private javax.swing.JButton btnTablaReservas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
